name: Automated API tests using Postman CLI

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - stage
      - dev

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API Tests with Collection/Folder - Demo
        run: |
          postman collection run ./postman/collections/SafeStar\ Service\ Testing/Workflow\ Tests/Scenario\ 1\ -\ Successful\ startup\ and\ safety\ check\ with\ message\ display\ for\ existing\ driver\ and\ vehicle -e ./postman/environments/Test.environment.yaml --env-var jwtSecret=YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc= --env-var driverID=1001 --env-var vehicleID=1002 --report-events
          postman collection run ./postman/collections/SafeStar\ Service\ Testing/Workflow\ Tests/Scenario\ 1\ -\ Successful\ startup\ and\ safety\ check\ with\ message\ display\ for\ existing\ driver\ and\ vehicle -e ./postman/environments/Prod.environment.yaml --env-var jwtSecret=YS1zdHJpbmctc2VjcmV0LWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc= --env-var driverID=1001 --env-var vehicleID=1002 --report-events
      - name: Run API Tests with Monitor
        run: |
          postman monitor run "<REPLACE_THIS_WITH_YOUR_MONITOR_ID>"
        continue-on-error: true
      - name: Lint Service Specification
        run: |
          postman spec lint ./postman/specs/SafeStar_Spec.yaml -f error
